### ISSUE TITLE
connection string is unnecessarily limited

### ISSUE THREAD

**Issue by jayvdb** [kurotych/sqlant#16]
If I do
```diff
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -20,9 +20,9 @@ pub trait ViewGenerator {
 }

 pub fn lookup_parser(connection_string: &str, schema_name: String) -> Box<dyn SqlERDataLoader> {
-    if connection_string.starts_with("postgres") {
+    //if connection_string.starts_with("postgres") {
         return Box::new(PostgreSqlERDLoader::new(connection_string, schema_name));
-    }
+    //}
     panic!("Appropriate parser is not found :(");
 }

```
I can connect with a connection string like
`host=/tmp/.tmpFXjbNd user=postgres dbname=butane_test_2d8e5d818d914100a098817c08599faf`

This is the connection string style used by https://github.com/Electron100/butane , which I would like to use together with sqlant

**Comment by kurotych** [comment]
Hi @jayvdb 
I agree with you we can do this.
Would you like to prepare PR?

**Comment by jayvdb** [comment]
Ok, I can do it.
