### ISSUE TITLE
Error in generated PlantUML

### ISSUE THREAD

**Issue by jayvdb** [kurotych/sqlant#23]
```
Error found in diagram erd
ERROR
5
Syntax Error?
Some diagram description contains errors
```
The generated source is

```plantuml
@startuml 

hide circle
skinparam linetype ortho

"**butane_migrations**" {
# <b>""name""</b>: //""text"" <b><color:goldenrod>(PK) </color></b><b><color:DarkRed>(NN) </color></b> //
---
}

@enduml
```

**Comment by jayvdb** [comment]
Unfortunately not.

The table DDL for one of the tables, the one mentioned above, is
```sql
CREATE TABLE IF NOT EXISTS butane_migrations (
"name" TEXT NOT NULL PRIMARY KEY
);
```

**Comment by kurotych** [comment]
Thanks @jayvdb
This is enough for reproduce. I will fix

**Comment by jayvdb** [comment]
I suspect the problem is that because there are no relationships between entities, plantuml doesnt detect the type of diagram, and fails.

The mermaid diagram shows each table separately.  i.e. disconnected.

**Comment by jayvdb** [comment]
I've added all the relationships, and the mermaid diagram looks well connected.  The plantuml is still failing to render.

**Comment by kurotych** [comment]
> The plantuml is still failing to render.

I've found at least one reason Plantuml has failed. It now required the "class" keyword.
Fixing...

**Comment by kurotych** [comment]
@jayvdb could you try this fix?
https://github.com/kurotych/sqlant/pull/24/files#diff-d94002e7bd41ac4a55adfe026b3b0b387c251b5fe1d2857e9aa7cd58f0276212

**Comment by kurotych** [comment]
I will release version 0.3 today

**Comment by kurotych** [comment]
New version is released https://crates.io/crates/sqlant
