### ISSUE TITLE
Add legend

### ISSUE THREAD

**Issue by jayvdb** [kurotych/sqlant#35]
It would be nice to have a legend for the terms used, or some optional way to supply a legend.
e.g.

```plantuml
 legend right
 <#GhostWhite,#GhostWhite>|        |= __Legend__ |
 |<color:goldenrod> (PK) </color>| Primary Key |
 |<color:701fc6> (FK) </color>| Foreign Key |
 |<color:DarkRed> (NN) </color>| Not Null |
 endlegend
```

**Comment by kurotych** [comment]
Hi @jayvdb.

I think we can add a CLI flag `--legend` with such description. 
I will do it  when I have a chance
