### ISSUE TITLE
sqlant generates empty diagramm

### ISSUE THREAD

**Issue by dontspeak** [kurotych/sqlant#8]
I have a db with plenty of schemas and table, but all I get is an empty diagramm? I'm working unter Windows10 command line:

```
c:\TEMP>sqlant postgresql://<USER>:<PWD>@localhost:5440/rlptest
@startuml

hide circle
skinparam linetype ortho



@enduml


c:\TEMP>
```

**Comment by kurotych** [comment]
Hello @dontspeak. Thank you for the report. 

Could you provide me database schema and PSQL version?
I want to try to reproduce this problem.

**Comment by dontspeak** [comment]
Hi!
actually I found out something interesting: When I try to create a diagramm with plan _planter_ 

`planter postgresql://<USER>:<PWD>@localhost:5440/rlptest?sslmode=disable -o example.uml`

I get the same empty result! But when I add the schema

`planter -s myschema1 postgresql://<USER>:<PWD>@localhost:5440/rlptest?sslmode=disable -o example.uml`

I works. So maybe sqlant should be able to pass through the schema name as well?

**Comment by kurotych** [comment]
I think I understand the problem

> So maybe sqlant should be able to pass through the schema name as well?

Yes, you are right. I'll add such a CLI option and will try to fix your problem soon. 
I'll update you as soon as I have a result

**Comment by kurotych** [comment]
Hello @dontspeak 
I've added support of -s, --schema cli options to the main branch. 

Could you build the latest main version and try to run? 
`sqlant -s myschema1 postgresql://<USER>:<PWD>@localhost:5440/rlptest?sslmode=disable`

**Comment by dontspeak** [comment]
Hi! I'm sorry, but I'm not very familiar with Rust. When I try to compile the source, I get `maybe a missing crate `clap`?`

Before, I just installed it via Cargo.

**Comment by kurotych** [comment]
@dontspeak No problem, I'll release a new version in a few hours to make it possible to install last updates via Cargo

**Comment by kurotych** [comment]
The new version of sqlant (v0.1.4) has been released.
You can try

**Comment by dontspeak** [comment]
Hi, yes works now, thank you so much for your quick help!
